---
title: "Gitting Started"
subtitle: "⚔<br/>Learning Git"
author: "Nick Solomon"
date: "October 17, 2018"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: center, middle, inverse

```{r xaringan-themer, include = FALSE}
library(xaringanthemer)
mono_light(
  base_color = "#265a88",
  white_color = "#FFFFFF"
)
```

# Why Git?

---

## Why Git?
--

- Versioning
--

- Collaboration

---

class: center, middle, inverse

# Setting up Git

---

## Config
--

```bash
$ git config --global user.name "Your Name"
$ git config --global user.email "you@council.nyc.gov"
$ git config --global credential.helper wincred
```

---

class: center, middle, inverse

# Repos

---

## What is a repo?
--

- A folder
--

- Plus magic!
--

  - The `.git` directory
--

- Contains all changes to tracked files
--

- You can only track files within the repo!
---

## What is a repo?
--

```bash
$ ls -a
```
--

```bash
.  ..
```
--
```bash
$ git init
$ ls -a
```
--

```bash
.  ..  .git
```

---

class: center, middle, inverse

# Staging and commits

---

## Git workflow
--

1. Create, edit, and save files
--

2. *Stage* changes
--

3. *Commit* changes
---

## Seeing what's up
--

```bash
*$ git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        my_file.txt

nothing added to commit but untracked files present (use "git add"
to track)
```

---
## Staging changes
--

- `git add` pulls double duty
--

- Use `git add <file>` to start tracking files
--

  - Let Git know you care about this particular file
--

- Use `git add <file>` to stage changes
--

  - Let Git know you've made changes to a file and you want to save them soon
--

  - Adds a file to the *index*
---

## Commits
--

- A snapshot of your repo
--

- Should be a small, complete unit of work
--

- `git commit` saves everything that's staged
--

- Opens a text editor to write a *commit message*
--

  - A short description of your changes
--

  - Good: `"Wrote function to parse date column."`
--

  - Bad: `"Did whole analysis."`
--

  - Worse: `"skjdafasklj"`

---

## Review
--

- `git add <files>` to stage changes
--

- `git commit` to save changes
--

- Write a commit message

---

## The shortcut
--

```bash
git commit -am "Message"
```
--

- `-a`: Add all changes to files that are already tracked
--

- `-m`: Use the following string as my commit message

---
class: center, middle, inverse

# History

---

## Viewing history
--

- Git lets you view the history of your entire project
--


```bash
*$ git log
commit 0628f46c7baffc01775e7d2ed8ac8b9ea6a88b45 (HEAD -> master)
Author: Nick Solomon <NSolomon@council.nyc.gov>
Date:   Thu Oct 11 16:08:37 2018 -0400

    staging and committing

commit 3d4475c1c7bc4acfad48768fdb1de275f25c019a
Author: Nick Solomon <NSolomon@council.nyc.gov>
Date:   Thu Oct 11 15:19:54 2018 -0400

    a few sections

commit 41c2f89bcc5b5e22a3b4fcea18c44a36a8ce9695
Author: Nick Solomon <NSolomon@council.nyc.gov>
Date:   Thu Oct 11 14:50:06 2018 -0400

    first commit
```
--

- Date, time, author, message
---

## Going back in time
--

- Explore the past
--
  
  - `git checkout <commit> [<file>]`
--

  - Makes the repo (or a file) as it was at `<commit>`
--

- Return to the near past
--
  
  - `git reset <--hard|--soft|--mixed> <ref> [<file>]`
--
  
  - Undoes committed changes
--

  - With `<file>` unstages a file
--

- Return to the far past
--

  - `git revert <commits>`
--
  
  - Creates "inverse" commits
--

- **Warning**: Here be dragons
---

class: center, middle, inverse

# Remotes

---

## Enter the cloud
--

- Another Git repo connected to yours
--

- Collaboration
--

- Backups
---

## GitHub
--

- Create a repo on GitHub
--

- `git clone`
--

  - Copy a remote repo to your computer
--

  - Create a connection between your repo and the remote

---

## Remote operations
--

- `git pull`
--

  - Gather commits from the remote and apply them to your local copy
--

- `git push`
--

  - Put your commits on the remote

---
class: center, middle, inverse

# Branches

---
## What is a branch
--

- A playground
--

- A separate timeline where you can play around without bothering other people

---

## Using branches
--

- `git branch <branch-name>`
--

  - Creates a new branch at the current commit
--

- `git checkout <branch-name>`
--

  - Switch to a new branch
--

  - Make changes, commit things, have fun
--

- `git checkout -b <branch-name>`
--

  - Create new branch and switch to it

---

## Branches and remotes
--

- `git push <remote> <branch>`
--

  - Push commits on a branch to a remote
--

  - Creates new branch on remote if it doesn't exist
--

- `git push -u <remote> <branch>`
--

  - Push commits on branch to a remote
--

  - `-u`: Set the new branch on the remote as "upstream"
--

  - Create a link between your branch and the branch on the remote

---

## Branches and remotes
--

- `git pull <remote> <branch>`
--
  - Pull changes on branch from remote
--

- `git pull`
--

  - Pulls from your branches upstream branch

---

## Merges
--

- Put commits from one branch onto another branch
--

- You're done playing and you want everyone to see what you did
--

- `git merge <branch>`
--

  - Merge changes on branch into currently checked out branch
--


```bash
$ git checkout master
$ git merge my-branch
```
--

- Creates a "merge commit"
---
class: center, middle, inverse

# Conflicts

---

class: center, middle, inverse

# The danger zone

---

class: center, middle, inverse

# Resources